# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-mongodb-nodejs-quickstart
metadata:
  template: cosmos-db-mongodb-nodejs-quickstart

hooks:
  postprovision:
    posix:
      shell: sh
      run: |
        echo "sh: Creating root .env file from azd environment variables…"
        azd env get-values > .env
        eval "$(azd env get-values)"
        echo "Running AdventureWorks setup script…"
        ./scripts/create-adventureworks.sh
        
    windows:
      shell: pwsh
      run: |
        Write-Host "pwsh: Creating root .env file from azd environment variables…"
        azd env get-values > .env
        Invoke-Expression "azd env get-values"
        Write-Host "Running AdventureWorks setup script…"
        ./scripts/create-adventureworks.sh


services:
pipeline:
  provider: github